-- Script para crear o modificar la tabla imagenes correctamente

-- 1. Verificar si la tabla imagenes existe
SELECT EXISTS (
   SELECT FROM information_schema.tables 
   WHERE table_name = 'imagenes'
);

-- 2. Crear la tabla imagenes si no existe
CREATE TABLE IF NOT EXISTS imagenes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  url TEXT NOT NULL,
  bus_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Agregar restricción de clave foránea si no existe
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'imagenes_bus_id_fkey'
  ) THEN
    ALTER TABLE imagenes
    ADD CONSTRAINT imagenes_bus_id_fkey
    FOREIGN KEY (bus_id) REFERENCES buses(id) ON DELETE CASCADE;
  END IF;
END
$$;

-- 4. Verificar estructura actualizada de la tabla imagenes
SELECT column_name, data_type, column_default, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'imagenes';

-- 5. Verificar estructura de bus_estacion
SELECT column_name, data_type, column_default, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'bus_estacion';

-- 6. Verificar todas las restricciones
SELECT 
    con.conname AS constraint_name,
    con.contype AS constraint_type,
    pg_get_constraintdef(con.oid) AS constraint_definition
FROM 
    pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
WHERE 
    rel.relname IN ('buses', 'imagenes', 'bus_estacion');
